Added current score display
TiagoDanin/Rock-Paper-Scissors-Web pull request #30
Opened 2020-10-07 22:14 UTC by michalStarski

Ad. #29

2020-10-08 03:02 UTC, TiagoDanin commented
@michalStarski avoid issues already assigned

2020-10-09 01:04 UTC, TiagoDanin requested changes

2020-10-09 01:04 UTC, TiagoDanin commented on package-lock.json
> +{
Pls remove `package-lock.json`
No use NPM, use Yarn.
`yarn install`
`yarn build`

2020-10-09 14:42 UTC, michalStarski commented
Hey! I thought you wouldn't review my changes since the issue has been assigned to someone else. With that in mind i accidentally already deleted my fork so I had to create another one. Since I can't go back to this PR I've created another one with the same changes + requested changes to it. It's avaliable here:

#31

Please, take a look and sorry for any inconvenience,

2020-10-09 15:30 UTC, TiagoDanin commented
> Hey! I thought you wouldn't review my changes since the issue has been assigned to someone else. With that in mind i accidentally already deleted my fork so I had to create another one. Since I can't go back to this PR I've created another one with the same changes + requested changes to it. It's avaliable here:
> 
> #31
> 
> Please, take a look and sorry for any inconvenience.
> 
> (Of course after review you can close this one)

No problem :)

2020-10-09 15:30 UTC, closed without merging